package com.acl.easymeal.modelo

import android.graphics.Bitmap
import androidx.room.Entity
import androidx.room.PrimaryKey


@Entity(tableName = "Recetas")
data class Receta(
    @PrimaryKey(autoGenerate = true) val id:Int,
    val nombreReceta:String,
    val descripcion:String,
    val imagen_text:String,
    var imagen:Bitmap,
    val categoria:String,
    val ingrediente1:String,
    val ingrediente2:String,
    val ingrediente3:String,
    val ingrediente4:String,
    val ingrediente5:String,
    val ingrediente6:String,
    val ingrediente7:String,
    val ingrediente8:String,
    val ingrediente9:String,
    val ingrediente10:String,
    val ingrediente11:String,
    val ingrediente12:String,
    val cantidad_ingrediente1:String,
    val cantidad_ingrediente2:String,
    val cantidad_ingrediente3:String,
    val cantidad_ingrediente4:String,
    val cantidad_ingrediente5:String,
    val cantidad_ingrediente6:String,
    val cantidad_ingrediente7:String,
    val cantidad_ingrediente8:String,
    val cantidad_ingrediente9:String,
    val cantidad_ingrediente10:String,
    val cantidad_ingrediente11:String,
    val cantidad_ingrediente12:String,
    val duracion:Int,
    val paso1:String,
    val paso2:String,
    val paso3:String,
    val paso4:String,
    val paso5:String,
    val paso6:String,
    val paso7:String,
    val paso8:String,
    val paso9:String,
    val paso10:String,
    val paso11:String,
    val paso12:String,
    val paso13:String,
    val paso14:String,
    val paso15:String,
    val paso16:String,
    val paso17:String,
    val paso18:String,
    val paso19:String,
    val paso20:String,
    val idAutor:String,
    var num_ingredientes:Int,
    var num_pasos:Int,
    var dificultad:String
)
